server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: tenant1
#
#scrape_configs:
#  - job_name: docker
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: docker
#          __path__: /var/lib/docker/containers/*/*.log
#          __docker_container_name__: "manual"  # gets overwritten by pipeline
#    pipeline_stages:
#      - docker: {}
#      - labels:
#          container: container_name

#scrape_configs:
#  - job_name: system
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: varlogs
#          __path__: /var/log/*log
#
#  - job_name: docker
#    docker_sd_configs:
#      - host: unix:///var/run/docker.sock
#        refresh_interval: 5s
#    relabel_configs:
#      - source_labels: [__meta_docker_container_name]
#        target_label: container
#      - source_labels: [__meta_docker_container_label_com_docker_swarm_service_name]
#        target_label: service
#      - source_labels: [__meta_docker_container_image]
#        target_label: image
#      - source_labels: [__meta_docker_container_id]
#        target_label: container_id
#    pipeline_stages:
#      - docker: {}

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: '^/(.+)$'   # Remove leading slash from container names
        replacement: '$1'
      - source_labels: [__meta_docker_container_image]
        target_label: image
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
    pipeline_stages:
      - docker: {}
